name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:latest'
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: swift test
